language: node_js
node_js:
  - "8.0.0"
script: "npm test"

cache:
  directories:
  - $HOME/.npm

before_install:
- npm i -g npm@latest
- npm i -g npx
- npm install -g codecov

after_success:
  - codecov
